name = "RankAggregation"
uuid = "ab9d97fe-b3f0-4ed5-83d9-5747a4381b0c"
author = "JÃºlio Hoffimann <julio.hoffimann@gmail.com>"
version = "0.1.0"

[deps]
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"

[compat]
Tables = "1.0"
julia = "1"

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DataFrames","Test"]
